spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/song-hm/config-repo
          username: song-hm
          password: XXXXXXX
          basedir: D:/Program/git/springcloud-sell/basedir
  rabbitmq:
    host: 192.168.25.132
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
